#!/bin/bash
read -p " [+] ป้อนชื่อผู้ใช้ที่คุณต้องการลบ: " username
egrep "^$username" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
# proses mengganti passwordnya
userdel -f $username
clear
  echo "----------------------- พัฒนาโดย คุณเต้ ทารุมะ (เต้เล็ก) -----------------------"
  echo "                        -----------------------------------------------"
  echo -e "  [+] ชื่อผู้ใช้ $username ถูกลบเรียบร้อยแล้ว "
  echo "                        -----------------------------------------------"
else
echo " [+] ไม่พบชื่อผู้ใช้บนเซิร์ฟเวอร์ของคุณ"
    exit 1
fi