#!/bin/bash
read -p "USERNAME ที่ต้องการเปลี่ยนรหัส : " username
egrep "^$username" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
read -p "ป้อนรหัสผ่านใหม่ $username: " password

clear
echo "กำลังเปลี่ยน Password..."
sleep 0.5
  egrep "^$username" /etc/passwd >/dev/null
  echo -e "$password\n$password" | passwd $username
  clear
  echo "----------------------- พัฒนาโดย SUPERNET-VPN.COM -----------------------"
  echo " "
  echo " "
  echo "---------------------------------------"
  echo -e "รหัสผ่านสำหรับผู้ใช้ ${blue}$username${NC} เปลี่ยนรหัสเรียบร้อยแล้ว."
  echo -e "รหัสผ่านใหม่สำหรับผู้ใช้ ${blue}$username${NC} คือ ${red}$password${NC}"
  echo "--------------------------------------"
  echo " "

else
echo -e "Username ${red}$username${NC} ไม่พบใน VPS ของคุณ"
exit 0
fi
