#!/bin/bash
read -p " [+] ใส่ชื่อผู้ใช้งาน : " username
egrep "^$username" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
echo " [+] มีผู้ใช้นี้แล้ว"
exit 0
else
read -p " [+] ใส่รหัสผ่าน : " password
read -p " [+] ใส่วันใช้งาน (30) : " masa_aktif
MYIP=$(wget -qO- ipv4.icanhazip.com)
today=`date +%s`
masa_aktif_detik=$(( $masa_aktif * 86400 ))
saat_expired=$(($today + $masa_aktif_detik))
tanggal_expired=$(date -u --date="1970-01-01 $saat_expired sec GMT" +%Y/%m/%d)
tanggal_expired_display=$(date -u --date="1970-01-01 $saat_expired sec GMT" '+%d %B %Y')
clear
echo "กำลังเชื่อมต่ออยู่ byvpn.net..."
sleep 0.4
echo "การสร้างบัญชี..."
sleep 0.3
echo "กำลังสร้างโฮสต์..."
sleep 0.2
echo "การสร้างชื่อผู้ใช้ใหม่ของคุณ : $username"
sleep 0.2
echo "การสร้างรหัสผ่านสำหรับ : $username"
sleep 1


useradd $username
usermod -s /bin/false $username
usermod -e  $tanggal_expired $username
  egrep "^$username" /etc/passwd >/dev/null
  echo -e "$password\n$password" | passwd $username
  clear
  echo " "
  echo  "------------ พัฒนาโดย คุณเต้ ทารุมะ (เต้เล็ก) ------------" 
  echo " "
  echo  " [+]  ไอพี         : $MYIP"
  echo  " [+]  ชื่อผู้ใช้     : $username"
  echo  " [+]  รหัสผ่าน    : $password"
  echo  " [+]  ใช้งานได้   : $masa_aktif วัน"
  echo  " [+]  หมดอายุวันที่ : $tanggal_expired_display"
  echo  " [+]  OpenVPN    : 1194 "
  echo  " [+]  PPTPVPN    : 1732"
  echo  " [+]  OpenSSH    : 22,143"
  echo  " [+]  DropBear    : 109,110,443"
  echo  " [+]  SquidProxy   : 80,3128,8000,8080"
  echo  " [+]  Ovpn          : http://$MYIP:81/client.ovpn "
  echo " "
  echo  "------------ พัฒนาโดย คุณเต้ ทารุมะ (เต้เล็ก) ------------" 
  echo " "
fi
